#!/usr/bin/env bash

if [[ "$IMAGE_NAME" == *"compile"* ]]; then
  export NEW_IMAGE_NAME="$DOCKER_REPO:compile-$SOURCE_COMMIT"
else
  export NEW_IMAGE_NAME="$DOCKER_REPO:$SOURCE_COMMIT"
fi

docker tag $IMAGE_NAME $NEW_IMAGE_NAME
docker push $NEW_IMAGE_NAME

